export const PRIMARY = '#005275'
export const SECONDARY = '#3DA1CC'
export const WHITE = '#FFFFFF'
export const BLACK = '#1E1E1E'
export const RED = '#FF0000'
export const ORANGE = '#FFBA5A'
export const GREY = '#a9a9a9'
